export {
  DEFAULT_OTEL_CONFIG,
  LIBRARY_NAME,
  LIBRARY_VERSION,
  type iMessageOTelConfig,
} from "./config.js";

export {
  ATTR_ERROR_TYPE,
  ATTR_GATEWAY_ABORTED,
  ATTR_GATEWAY_DURATION_MS,
  ATTR_GATEWAY_ERRORS,
  ATTR_GATEWAY_MESSAGES_RECEIVED,
  ATTR_SERVICE_NAME,
  ATTR_IMESSAGE_ATTACHMENT_COUNT,
  ATTR_IMESSAGE_CHAT_GUID,
  ATTR_IMESSAGE_HAS_ATTACHMENTS,
  ATTR_IMESSAGE_IS_GROUP_CHAT,
  ATTR_IMESSAGE_MESSAGE_ID,
  ATTR_IMESSAGE_MODE,
  ATTR_IMESSAGE_THREAD_ID,
  SPAN_ADD_REACTION,
  SPAN_DELETE_MESSAGE,
  SPAN_EDIT_MESSAGE,
  SPAN_FETCH_MESSAGES,
  SPAN_FETCH_THREAD,
  SPAN_FILES_CLEANUP,
  SPAN_FILES_WRITE_TEMP,
  SPAN_GATEWAY_LISTENER,
  SPAN_GATEWAY_RUNNER,
  SPAN_INITIALIZE,
  SPAN_MESSAGE_RECEIVE,
  SPAN_OPEN_MODAL,
  SPAN_POLL_VOTE_RECEIVE,
  SPAN_POST_MESSAGE,
  SPAN_REMOVE_REACTION,
  SPAN_SDK_CONNECT,
  SPAN_SDK_DISCONNECT,
  SPAN_SDK_SEND_ATTACHMENT,
  SPAN_SDK_SEND_MESSAGE,
  SPAN_START_TYPING,
  buildCommonAttributes,
  redactChatGuid,
} from "./attributes.js";

export { createTracer, withSpan, withSyncSpan } from "./tracer.js";

export { AdapterMetrics, NOOP_METRICS, createMeter } from "./metrics.js";

export { OTelLogger } from "./logger.js";
